# coding: utf-8

"""
    NabooApi V1

    Here you have the first version of the naboo api to create checkout automatically

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from naboo.models.transaction_response import TransactionResponse

class TestTransactionResponse(unittest.TestCase):
    """TransactionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransactionResponse:
        """Test TransactionResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransactionResponse`
        """
        model = TransactionResponse()
        if include_optional:
            return TransactionResponse(
                order_id = '',
                method_of_payment = [
                    ''
                    ],
                amount = 56,
                amount_to_pay = 56,
                currency = '',
                created_at = '',
                transaction_status = 'pending',
                is_escrow = True,
                is_merchant = True,
                checkout_url = ''
            )
        else:
            return TransactionResponse(
                order_id = '',
                method_of_payment = [
                    ''
                    ],
                currency = '',
                created_at = '',
                checkout_url = '',
        )
        """

    def testTransactionResponse(self):
        """Test TransactionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
