# coding: utf-8

"""
    NabooApi V1

    Here you have the first version of the naboo api to create checkout automatically

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from naboo.models.get_account_response import GetAccountResponse

class TestGetAccountResponse(unittest.TestCase):
    """GetAccountResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAccountResponse:
        """Test GetAccountResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAccountResponse`
        """
        model = GetAccountResponse()
        if include_optional:
            return GetAccountResponse(
                account_number = '',
                balance = 1.337,
                account_is_activate = True,
                method_of_payment = 'WAVE',
                loyalty_credit = 56
            )
        else:
            return GetAccountResponse(
                account_number = '',
                balance = 1.337,
                account_is_activate = True,
                method_of_payment = 'WAVE',
                loyalty_credit = 56,
        )
        """

    def testGetAccountResponse(self):
        """Test GetAccountResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
