# coding: utf-8

"""
    NabooApi V1

    Here you have the first version of the naboo api to create checkout automatically

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from naboo.models.transaction_status_enum import TransactionStatusEnum

class TestTransactionStatusEnum(unittest.TestCase):
    """TransactionStatusEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionStatusEnum(self):
        """Test TransactionStatusEnum"""
        # inst = TransactionStatusEnum()

if __name__ == '__main__':
    unittest.main()
