# coding: utf-8

"""
    NabooApi V1

    Here you have the first version of the naboo api to create checkout automatically

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from naboo.models.delete_transaction_response import DeleteTransactionResponse

class TestDeleteTransactionResponse(unittest.TestCase):
    """DeleteTransactionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeleteTransactionResponse:
        """Test DeleteTransactionResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeleteTransactionResponse`
        """
        model = DeleteTransactionResponse()
        if include_optional:
            return DeleteTransactionResponse(
                order_id = '',
                message = ''
            )
        else:
            return DeleteTransactionResponse(
                order_id = '',
                message = '',
        )
        """

    def testDeleteTransactionResponse(self):
        """Test DeleteTransactionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
