# coding: utf-8

"""
    NabooApi V1

    Here you have the first version of the naboo api to create checkout automatically

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from naboo.api.transaction_service import TransactionService


class TestTransactionService(unittest.TestCase):
    """TransactionService unit test stubs"""

    def setUp(self) -> None:
        self.api = TransactionService()

    def tearDown(self) -> None:
        pass

    def test_create_transaction_transaction_create_transaction_post(self) -> None:
        """Test case for create_transaction_transaction_create_transaction_post

        Create Transaction
        """
        pass

    def test_delete_transaction_transaction_delete_transaction_delete(self) -> None:
        """Test case for delete_transaction_transaction_delete_transaction_delete

        Delete Transaction
        """
        pass

    def test_get_one_transaction_transaction_get_one_transaction_get(self) -> None:
        """Test case for get_one_transaction_transaction_get_one_transaction_get

        Get One Transaction
        """
        pass

    def test_get_transactions_transaction_get_transactions_get(self) -> None:
        """Test case for get_transactions_transaction_get_transactions_get

        Get Transactions
        """
        pass


if __name__ == '__main__':
    unittest.main()
