# coding: utf-8

"""
    NabooApi V1

    Here you have the first version of the naboo api to create checkout automatically

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from naboo.api.cashout_service import CashoutService


class TestCashoutService(unittest.TestCase):
    """CashoutService unit test stubs"""

    def setUp(self) -> None:
        self.api = CashoutService()

    def tearDown(self) -> None:
        pass

    def test_cash_out_orange_money_cashout_orange_money_post(self) -> None:
        """Test case for cash_out_orange_money_cashout_orange_money_post

        Cash Out Orange Money
        """
        pass

    def test_cash_out_wave_cashout_wave_post(self) -> None:
        """Test case for cash_out_wave_cashout_wave_post

        Cash Out Wave
        """
        pass


if __name__ == '__main__':
    unittest.main()
