# coding: utf-8

"""
    NabooApi V1

    Here you have the first version of the naboo api to create checkout automatically

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Wallet(str, Enum):
    """
    Wallet
    """

    """
    allowed enum values
    """
    WAVE = 'WAVE'
    ORANGE_MONEY = 'ORANGE_MONEY'
    FREE_MONEY = 'FREE_MONEY'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Wallet from a JSON string"""
        return cls(json.loads(json_str))


